# Generated by Django 4.0.6 on 2022-09-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
