# Generated by Django 4.0.6 on 2022-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_admin', '0002_bus_bus_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_photo',
            field=models.ImageField(max_length=55, null=True, upload_to=''),
        ),
    ]
